parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/caddy-logs
- ./parsers/s01-parse/barnoux/caddy-coraza.yaml
scenarios:
- ./scenarios/barnoux/coraza.yaml
postoverflows:
log_file: coraza.log
log_type: caddy
